from yacs.config import CfgNode as CN

_C = CN()

_C.MODEL = CN()
_C.MODEL.DEVICE = "cuda"
_C.MODEL.WEIGHT = ""
_C.MODEL.NUM_SAMPLES = 64
_C.MODEL.NUM_SAMPLES_FINE = 0

_C.MODEL.EMBEDDER = CN()
_C.MODEL.EMBEDDER.POSITION_DIM = 10
_C.MODEL.EMBEDDER.DIRECTION_DIM = 4

_C.MODEL.MLP = CN()
_C.MODEL.MLP.NUM_LAYERS = 8
_C.MODEL.MLP.SKIPS = [4, ]
_C.MODEL.MLP.POSITION_DIM = 60
_C.MODEL.MLP.DIRECTION_DIM = 24
_C.MODEL.MLP.MIDDEL_DIM = 256
_C.MODEL.MLP.USE_VIEWDIRS = True

_C.MODEL.RENDER = CN()
_C.MODEL.RENDER.RAW_NOISE_STD = 0.0
